// demos/solid/src/pages/stars/[repo].jsx
import { createResource, Suspense } from "solid-js";
import { ErrorBoundary } from "solid-js/web";

const sleep = (ms) => new Promise(res => setTimeout(res, ms));

const fetchWithDelay = async (url, waitMs) => {
  await sleep(waitMs);
  const r = await fetch(url);
  return r.json();
};

const fetchStar = async (repo) => {
  const data = await fetchWithDelay(
    `https://api.github.com/repos/solidjs/${repo}`,
    500
  );
  return data.stargazers_count;
};

export default function App({repo}) {
  const [stars] = createResource(
    () => repo,
    fetchStar
  );

  return (
    <h2>
      GitHub Stars:{" "}
      <ErrorBoundary fallback={() => "🙀 Request failed."}>
        <Suspense fallback={"🌀 Loading..."}>
          ⭐️ {stars()}!
        </Suspense>
      </ErrorBoundary>
    </h2>
  );
}

// demos/react/src/pages/stars/[repo].jsx
import { Suspense, useState, useEffect } from "react";

// Helper to wrap a Promise for Suspense
function createResource(promise) {
  let status = "pending";
  let result;
  let suspender = promise.then(
    r => {
      status = "success";
      result = r;
    },
    e => {
      status = "error";
      result = e;
    }
  );
  return {
    read() {
      if (status === "pending") throw suspender;
      if (status === "error") throw result;
      return result;
    }
  };
}

// Fetch function
const fetchWithDelay = async (url, waitMs) => {
  await new Promise(res => setTimeout(res, waitMs));
  const r = await fetch(url);
  return r.json();
};

const fetchStar = (repo) =>
  createResource(fetchWithDelay(`https://api.github.com/repos/zikojs/${repo}`, 500).then(data => data.stargazers_count));

// StarContent just reads from resource
const StarContent = ({ resource }) => {
  const stars = resource.read(); // Suspense will handle pending
  return <span>⭐️ {stars}!</span>;
};

// App component
export default function App({ repo }) {
  const [resource, setResource] = useState(() => fetchStar(repo));

  useEffect(() => {
    setResource(fetchStar(repo));
  }, [repo]);

  return (
    <h2>
      GitHub Stars:{" "}
      <Suspense fallback={"🌀 Loading..."}>
        <StarContent resource={resource} />
      </Suspense>
    </h2>
  );
}
