// packages/create-ufbr/templates/preact-jsx/src/components/Delay.jsx
import { useEffect, useState } from "preact/hooks";

export default function Delay({
  delay = 0,
  fallback = null,
  children,
}) {
  const [ready, setReady] = useState(delay === 0);

  useEffect(() => {
    if (delay === 0) {
      setReady(true);
      return;
    }

    const timer = setTimeout(() => {
      setReady(true);
    }, delay);

    return () => clearTimeout(timer);
  }, [delay]);

  return ready ? children : fallback;
}

// create-ufbr/templates/solid-jsx/src/components/Delay.jsx
import { createSignal, onCleanup } from "solid-js";

export default function Delay(props) {
  const [ready, setReady] = createSignal(props.delay === 0);

  if (props.delay > 0) {
    const timer = setTimeout(() => setReady(true), props.delay);
    onCleanup(() => clearTimeout(timer));
  }

  return ready() ? props.children : props.fallback;
}
