// packages/create-ufbr/templates/vue-js/src/components/Delay.vue
<script setup>
import { ref, onMounted, onUnmounted } from "vue";

const props = defineProps({
  delay: {
    type: [Number, String],
    default: 0,
  },
});

const ready = ref(Number(props.delay) <= 0);

let timer;

onMounted(() => {
  const delay = Number(props.delay);

  if (delay > 0) {
    timer = setTimeout(() => {
      ready.value = true;
    }, delay);
  }
});

onUnmounted(() => {
  if (timer) {
    clearTimeout(timer);
  }
});
</script>

<template>
  <template v-if="ready">
    <slot />
  </template>

  <template v-else>
    <slot name="fallback">
      <p>Loading...</p>
    </slot>
  </template>
</template>

// create-ufbr/templates/svelte-js/src/components/Delay.svelte
<script>
  import { onMount, onDestroy } from "svelte";

  export let delay = 0;

  let ready = delay === 0;
  let timer;

  onMount(() => {
    if (delay > 0) {
      timer = setTimeout(() => {
        ready = true;
      }, delay);
    }
  });

  onDestroy(() => {
    if (timer) clearTimeout(timer);
  });
</script>

{#if ready}
  <slot />
{:else}
  <slot name="fallback" />
{/if}
