// create-ufbr/templates/vue-js/src/components/Delay.vue
<script setup>
import { ref, onMounted, onUnmounted } from "vue";

const props = defineProps({
  delay: {
    type: Number,
    default: 0,
  },
  fallback: {
    default: null,
  },
});

const ready = ref(props.delay === 0);
let timer;

onMounted(() => {
  if (props.delay > 0) {
    timer = setTimeout(() => {
      ready.value = true;
    }, props.delay);
  }
});

onUnmounted(() => {
  if (timer) clearTimeout(timer);
});
</script>

<template>
  <slot v-if="ready" />
  <component v-else :is="fallback" />
</template>

// create-ufbr/templates/svelte-js/src/components/Delay.svelte
<script>
  export let delay = 0;
  export let fallback = null;

  let ready = delay === 0;

  const timer = delay > 0
    ? setTimeout(() => {
        ready = true;
      }, delay)
    : null;

  import { onDestroy } from "svelte";

  onDestroy(() => {
    if (timer) clearTimeout(timer);
  });
</script>

{#if ready}
  <slot />
{:else}
  {@html fallback}
{/if}
